language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
script: npm test
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: OFsIjKueRPtZOCqwhn+OwplzN8J0FhCMMrn245Ev3KTKcYbjiS58J6nlsjx32zIBstdGIOD/7rcpEoW1vWk/5G3b257VUsVZMGvox9C+cClswNYq6jzSj5MSommwIMbSgtZUImwI/bA+6DKz0YGrglOX/diCIdSbJkIF+t5pa937HAAoRjPnyD9MapvNU8dEUTOgJzj1r1hsy5OJeRl6uyBmJpkAscpJ5sB3/cpEH40o7zc9iysr2hii58mm9hF05t+a6uEDTCazIkn6pcfBAD92CCjjfRUWUydnNZm6DoziTduaV9VPELZT1kta4Ql9Q3SzqlELRTD4db4pISonTQ/mhmjBdP+wFuHxtw3ihf2lhrxFZXnJXwI0sZK62aXKq/igTOrxzzbMni1huSOhxMrMNxSdwQ6PZ1j+d1BeyHmpYAIFF0WwnaMuaUGqzQRI2sRpwSwBzk0MZUK6dM9ee3b1wk6VneXIxep5But8R3D0n+N//zLZZWapkwtShvv98TN4NpSRwjz+Da+BB9MUNhk6RkPzpaxTy8RvdHMsy7GpFR8Ad3nJ8KNRla6yn25OQxgXcPVZXq+2BC9KfSLdypQeosHESDz4gjlWad7mK8C1YBxrRkOHuEFEfiULVP8B2G6YRmpAaZrwMnRoeSSukm/2ARp0jXNOnFUBxGlOGZU=
  on:
    tags: true
    node: 5
